-- ============================================================================
-- Etapa 5 · Fatia 3 (quotes) — Q2 (2/2): UNIQUE (workspace_id, source_local_id)
-- ============================================================================
-- Backstop de idempotência do import: no máximo UMA linha por
--   (workspace_id, source_local_id). É o arbiter do
--   ON CONFLICT (workspace_id, source_local_id) usado dentro do RPC
--   public.import_quote_with_items() (arquivo seguinte).
--
-- >>> NÃO-PARCIAL de propósito: um índice único PARCIAL (WHERE source_local_id IS
--     NOT NULL) quebra a inferência do arbiter no ON CONFLICT — precedente P8b
--     (wa_message_id) e já replicado na Fatia 2 (ux_crm_opp_source_local). Como
--     NULLs são DISTINTOS por padrão no Postgres, este índice não-parcial permite
--     ilimitadas linhas legadas com source_local_id NULL sem conflito.
--
-- >>> APLICAÇÃO (IMPORTANTE): CREATE INDEX CONCURRENTLY NÃO roda dentro de
--     transação. Este arquivo NÃO contém BEGIN/COMMIT. Aplique em AUTOCOMMIT
--     (Supabase Dashboard > SQL Editor, ou `psql "$DATABASE_URL" -f <arquivo>`).
--     NÃO aplique via `supabase db push`.
--
-- >>> PRÉ-REQUISITO: aplicar ANTES 20260719001200 (a coluna) e rodar a checagem
--     de pré-aplicação (docs/database/etapa-5-fatia-3-preaplicacao.sql, query 4):
--     todas as linhas devem ter source_local_id IS NULL (coluna recém-criada) —
--     logo não há como haver duplicata na criação do índice. Se o CONCURRENTLY
--     falhar, ele deixa um índice INVÁLIDO -> rode
--       DROP INDEX IF EXISTS public.ux_quotes_source_local;
--     e recrie. Confirme depois com pg_index (indisvalid = true, indisunique = true)
--     — gate 3 do protocolo (docs/qa/protocolo-homologacao.md).
-- ============================================================================

CREATE UNIQUE INDEX CONCURRENTLY IF NOT EXISTS ux_quotes_source_local
  ON public.quotes (workspace_id, source_local_id);
