// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewamvzncsloagtcvkbxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3YW12em5jc2xvYWd0Y3ZrYnh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYyMjI3MDcsImV4cCI6MjA5MTc5ODcwN30.1mbT5JdDAYJlQrzTFFHK2rp02PKQlyinZ-SF97tr9Cw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});